### ISSUE TITLE
Presentation link is broken

### ISSUE THREAD

**Issue by 4vir4l** [lundmb/Sagan2016#1]
Great work! I noticed the presentation file has been deleted. Could it please be re uploaded? Much appreciated!

**Comment by timothy-s-banks** [comment]
I believe that there is a PPT version and a PDF version in the archive that you could use. I don't know the status of the Google version of the presentation, it is probably gone for good now.  This work was done long ago.  I have added a comment to the README that the link is no longer active.

**Comment by 4vir4l** [comment]
I’ve reviewed the PPT but not the PDF, will check it out. Thank you for letting me know and for making the edit to the README.
